# Generated by Django 6.0.4 on 2026-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='High Profile Private Secondary School', max_length=200)),
                ('short_name', models.CharField(default='HPSS', max_length=20)),
                ('motto', models.CharField(default='Excellence in Education', max_length=200)),
                ('address', models.CharField(default='Zomba, Malawi', max_length=300)),
                ('phone', models.CharField(default='+265 1 234 567', max_length=20)),
                ('email', models.EmailField(default='info@highprofile.edu.mw', max_length=254)),
                ('primary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('secondary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('theme', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('custom', 'Custom')], default='blue', max_length=20)),
            ],
            options={
                'verbose_name': 'School Settings',
            },
        ),
    ]
