# Generated by Django 6.0.4 on 2026-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Short summary shown on listing', max_length=500)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('admissions', 'Admissions'), ('academics', 'Academics'), ('events', 'Events'), ('sports', 'Sports'), ('infrastructure', 'Infrastructure'), ('meetings', 'Meetings'), ('other', 'Other')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
